baseURL = "/"
languageCode = "ko-kr"
title = "Ballast I&C | 콘텐츠 마케팅 에이전시 밸러스트아이앤씨"
theme = "biztrox-hugo"
summaryLength = "20"

# navigation
[menu]
    
    [[menu.nav]]
    name = "About"
    URL = "/about"
    weight = 4
    
    [[menu.nav]]
    name = "Service"
    URL = "/service"
    weight = 3
    
    [[menu.nav]]
    name = "Insights"
    URL = "/insights"
    weight = 1
    
    [[menu.nav]]
    name = "How It Works"
    URL = "/howitworks"
    weight = 2
#    
#    [[menu.nav]]
#    name = "Team"
#    URL = "/team"
#    weight = 6
    
#    [[menu.nav]]
#    name = "Pricing"
#    URL = "/pricing"
#    weight = 7
    
#    [[menu.nav]]
#    name = "Contact"
#    URL = "/contact"
#    weight = 4


[taxonomies]
tag = "tags"
category = "categories"


[params]
logo = "images/logo.png"
#mail = "contact@ballast.co.kr"
#mobile = "0269710615"
searchIcon = "ti-search"
home = "Home"
# google map
#gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBI14J_PNWVd-#m0gnUBkjmhoQyNyd7nllA"
#mapLatitude = "51.5223477"
#mapLongitude = "-0.1622023"
#mapMarker = "images/marker.png"
baseURL = "/"

    # Quote Button
    [params.quoteBtn]
    enable = true
    btnText = "Contact"
    btnURL = "/contact"

    # about
    [params.about]
    enable = true
    bgImage = "images/background/about-bg.jpg"
    title = "Who We Are?"
    description = "Excepteur sint occaecat cupidatat non proident sunt culpa qui officia deserunt mollit anim id est laborum."
    [params.about.btn]
    enable = true
    btnText = "Explore More"
    btnURL = "#"

        [[params.about.listLeft]]
        listItem = "Business Services"

        [[params.about.listLeft]]
        listItem = "Audit & Assurance"
        
        [[params.about.listLeft]]
        listItem = "IT Control Solutions"

        [[params.about.listRight]]
        listItem = "Business Services"

        [[params.about.listRight]]
        listItem = "Audit & Assurance"
        
        [[params.about.listRight]]
        listItem = "IT Control Solutions"

    # promo video
    [params.promoVideo]
    enable = true
    heading = "We Are Alawys <br> Comited"
    videoURL = "https://www.youtube.com/watch?v=6ZfuNTqbHE8"
    title = "Lorem ipsum dolor <br> sit amet con."

    # cta
    [params.cta]
    enable = true
    bgImage = "images/background/cta.jpg"
    title = "Biztrox give the smart solution for your business"
    btnText = "get a quote"
    btnURL = "#"

    # clients Logo Slider
    [params.logoSlider]
    enable = true
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-1.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-2.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-3.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-4.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-5.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-1.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-2.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-3.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-4.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-5.png"
        URL = "#"

    # footer
    [params.footer]
    logo = "images/logo-footer.png"
    content = "콘텐츠 마케팅 에이전시 밸러스트아이앤씨. 클라이언트의 성장과 지속을 함께 고민하고, 경험과 관점을 공유하며, 성과와 데이터를 중심으로 일합니다."

    # service links
    services = "What We Do"
    
    # quickLinks
    quickLink = "Links"

    # subscribe
    subscribe = "이메일 구독"
    subscribeContent = "2주에 한 번씩 밸러스트 웹사이트에 올라오는 인사이트를 이메일로 구독하세요"

    # copyright
    copyright = "Ballast I&C</span> &copy; 2019 All Right Reserved"

        # social icon
        [[params.footer.socialIcon]]
        icon = "ti-facebook"
        URL = "#"

        [[params.footer.socialIcon]]
        icon = "ti-twitter-alt"
        URL = "#"
        
        [[params.footer.socialIcon]]
        icon = "ti-vimeo-alt"
        URL = "#"
        
        [[params.footer.socialIcon]]
        icon = "ti-linkedin"
        URL = "#"

        # service links
        [[params.footer.service]]
        serviceItem = "Company History"
        URL = "#"
        
        [[params.footer.service]]
        serviceItem = "About Us"
        URL = "#"
        
        [[params.footer.service]]
        serviceItem = "Contact Us"
        URL = "#"
        
        [[params.footer.service]]
        serviceItem = "Service"
        URL = "#"
        
        [[params.footer.service]]
        serviceItem = "Privacy Policy"
        URL = "#"

        # quick links
        [[params.footer.quickLinks]]
        quickLinkItem = "Pricing"
        URL = "#"
        
        [[params.footer.quickLinks]]
        quickLinkItem = "FAQs"
        URL = "#"
        
        [[params.footer.quickLinks]]
        quickLinkItem = "Contact Us"
        URL = "#"
        
        [[params.footer.quickLinks]]
        quickLinkItem = "Service"
        URL = "#"
        
        [[params.footer.quickLinks]]
        quickLinkItem = "Privacy Policy"
        URL = "#"

        # bottom links
        [[params.footer.links]]
            name = "Legal"
            URL = "#"
            
        [[params.footer.links]]
            name = "Sitemap"
            URL = "#"
            
        [[params.footer.links]]
            name = "Privacy Policy"
            URL = "#"
            
        [[params.footer.links]]
            name = "Terms & Conditions"
            URL = "#"

    # share blog post
    [[params.sharePost]]
    icon = "ti-facebook"
    URL = "#"
    
    [[params.sharePost]]
    icon = "ti-twitter-alt"
    URL = "#"
    
    [[params.sharePost]]
    icon = "ti-linkedin"
    URL = "#"
    
    [[params.sharePost]]
    icon = "ti-google"
    URL = "#"
        


